const titleMap = {
  _id: "Form ID",
  updatedAt: "Submitted/Updated Date",
  title: "Title",
  name: "Full Name",
  address: "Address",
  postcode: "Postcode",
  phone: "Phone",
  workPhone: "Work phone",
  homePhone: "Home phone",
  occupation: "Occupation",
  overSixteen: "Over 16",
  mobile: "Mobile",
  email: "Email Address",
  dogName: "Name of dog they are enquiring about",
  dogSize: "What size of dog they want",
  dogType: "What type of dog they want",
  dogAge: "What age of dog they want",
  dogSex: "What sex of dog they want",
  catName: "Name of cat they are enquiring about",
  catAge: "What age of cat they want",
  catType: "What type of cat they want",
  catColour: "What colour of cat they want",
  catSex: "What sex of cat they want",
  catAllergy: "Anyone in the household have an allergy to cat fur",
  homeType: "Their home is a",
  rentOrOwn: "Rent or own ",
  townOrCountry: "Town or Country",
  nextToRoad: "Home next to road",
  gardenOrYard: "Do they have a garden or yard",
  gardenOrYardSize: "Size of garden or yard",
  fullyEnclosed: "Yard fully enclosed",
  fenceHeight: "Height of fence",
  numAdults: "Number of adults that live in their home",
  numChildren: "Number of children that live in their home",
  childrenAges: "Ages of children that live in their home",
  otherChildrenVisit: "Do other children visit",
  otherChildrenAges: "Visiting childrens ages",
  otherChildrenVisitFrequency: "How often other children visit",
  retired: "Are they retired",
  baby: "Planning a baby",
  moving: "Planning on moving house",
  workHoursChange: "Planning a change in work hours",
  holiday: "Planning a holiday",
  dogReason: "Dog for indoors or outdoors",
  dogHomeAlone: "Will dog be left at home alone",
  dogHomeAloneHours: "How many hours per day will dog be left alone",
  dogHomeAloneFrequency: "How often will dog be left alone",
  catReason: "Cat for indoors or outdoors",
  catHomeAlone: "Will cat be left at home alone",
  catHomeAloneHours: "How many hours per day will cat be left alone",
  catHomeAloneFrequency: "How often will cat be left alone",
  exerciseType: "Exercise type dog will receive",
  exerciseTime: "How much daily exercise will they give the dog",
  dogSleepLocation: "Where will the dog sleep at night",
  ownOtherCurrentDogs: "Do they own other dogs",
  otherCurrentDogBreed: "Breed of other owned dog",
  otherCurrentDogNeutered: "Is their other dog neutered",
  otherCurrentDogTime: "How long have they had current dog",
  dogOwnOtherCurrentPets: "Do they own other pets",
  dogOtherCurrentPetTypes: "Types of other pets",
  ownOtherPastDogs: "Have they owned dogs in the past",
  otherPastDogTime: "How long ago did they last own dogs",
  otherDogFate: "What happened the past dog",
  dogAwareOfCostsAndLegal:
    "Aware of costs and legal implications of owning a dog",
  dogHowSoon: "How soon do they want a dog",
  dogFurtherInfo: "Further information provided",
  catSleepLocation: "Where will the cat sleep at night",
  ownOtherCurrentCats: "Do they own other cats",
  ownOtherCurrentPets: "Do they own other pets",
  otherCurrentPetTypes: "Types of other pets",
  ownOtherPastCats: "Have they owned cats in the past",
  otherPastCatTime: "How long ago did they last own cats",
  otherCatFate: "What happened the past cat",
  catAwareOfCostsAndLegal: "Aware of costs of owning a cat",
  catHowSoon: "How soon do they want a cat",
  catFurtherInfo: "Further information provided",
  date: "Date submitted",
  hearAboutUs: "How did they hear about Bright Eyes",
  other: "Other",
  followUp: "",
  houseVisit: "",
  appointment: "",
  emergencyContactTitle: "Emergency Contact Title",
  emergencyContactName: "Emergency Contact Name",
  emergencyContactRelationship: "Relationship to Emergency Contact",
  emergencyContactPhonePrimary: "Emergency Contact Primary Phone Number",
  emergencyContactPhoneSecondary: "Emergency Contact Secondary Phone Number",
  physicallyFit: "Are they physically fit",
  tetanus: "Have they had a Tetanus Booster in the last 10 years",
  healthConditionSpecialNeeds:
    "Health conditions or special needs that could affect ability to volunteer",
  healthConditionSpecialNeedsDetails:
    "Brief details of the health condition or special needs",
  workInterestedIn: "Work interested in",
  maxHours: "Max hours each week",
  timeSlot: "Commit to a specific time slot",
  daysOfTheWeek: "Days of the week they can help",
  employeeOrVolunteerAnimals:
    "Employee or volunteer eith any other charity/organization involved with the care of animals",
  refereeTitle: "Referee title",
  refereeName: "Referee name",
  refereeRelationship: "Referee relationship",
  refereeAddress: "Referee address",
  refereePostcode: "Referee postcode",
  refereePhone: "Referee phone",
  refereeEmail: "Referee email",
  offender: "Any unspent criminal convictions",
  offenderDetails: "Brief details of conviction",
  giftAidFuture: "Gift Aid future donations until further notice",
  giftAidPast:
    "Gift Aid previous donations for the current year, and all the previous four tax years",
  //* Subcategories
  aboutQuestions: "About Information",
  dogMatchingQuestions: "Dog Matching Information",
  catMatchingQuestions: "Cat Matching Information",

  homeQuestions: "Home Questions",
  //   gardenOrYardInfo: "",
  //   otherChildrenVisitInfo: "",
  //   planning: "",
  dogQuestions: "Dog Information",
  //   dogHomeAloneInfo: "",
  //   ownOtherDogsCurrentInfo: "",
  //   dogOwnOtherPetsCurrentInfo: "",
  //   ownOtherDogsPastInfo: "",

  catQuestions: "Cat Information",
  //   catHomeAloneInfo: "",
  //   ownOtherDogsCurrentInfo: "",
  //   dogOwnOtherPetsCurrentInfo: "",
  //   ownOtherDogsPastInfo: "",
  hearAboutUsInfo: "",
  emergencyContactInfo: "Emergency Contact Information",
  healthInfo: "Heslth Information",
  volunteeringInfo: "Volunteer Information",
  refereeInfo: "Referee Information",
  offenderInfo: "Offender Information",
};

export default titleMap;
